In [5]:
import numpy as np
a = [[11,12,13],[21,22,23],[31,32,33]]
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [57]:
print(np.ndim(A))
print(type(A))
print(np.max(A))
print(np.min(A))
print(np.mean(A))
print(np.shape(A))
print(np.size(A))

2
<class 'numpy.ndarray'>
33
11
22.0
(3, 3)
9


In [45]:
print(A[0])
print(A[0][0])
print(A[1][2])

[11 12 13]
11
23


In [53]:
A[0,0:2]

array([11, 12])

In [55]:
A[0:2,2]

array([13, 23])